#! /bin/bash

# Make sure the script is being executed with superuser privileges.
if [[ ${UID} -ne 0 ]] 
then
  echo "Executed with superuser (root) pls."
  exit 1
fi

sudo docker container run --rm -it -v <PATH_TO_SOURCE/Network_Monitor>:/home/network_monitor nghiaphamsg/network-monitor
